version: "3.8"

services:
  orthanc:
    build: ..
    ports: ["10042:8042"]
    restart: unless-stopped
    environment:
      ORTHANC__AUTHENTICATION_ENABLED: "false"
      ORTHANC__DICOM_AET: "ORTHANCFORWARDER"
      DESTINATION_URL: "http://orthanc-destination:8042/dicom-web"
      DESTINATION_USER: "demo"
      DESTINATION_PASSWORD: "demo"
      DESTINATION_LABEL: "MYLABEL"
      VERBOSE_ENABLED: "true"

  orthanc-destination:
    image: orthancteam/orthanc:24.5.1
    ports: ["10043:8042"]
    restart: unless-stopped
    environment:
      ORTHANC__AUTHENTICATION_ENABLED: "true"
      ORTHANC__DICOM_AET: "DESTINATION"
      VERBOSE_ENABLED: "true"
      ORTHANC_JSON: |
        {
          "RegisteredUsers" : {
            "demo" : "demo"
          },
          "DicomWeb" : {
              "Enable" : true
          }
        }